{{- if .Values.deployer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sa
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
  {{- with .Values.deployer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
